# Generated by Django 3.2.18 on 2023-05-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transport_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(verbose_name='id типа транспорта')),
                ('transport_number', models.CharField(max_length=100, verbose_name='номер транспорта')),
                ('owner_id', models.IntegerField(verbose_name='id владельца')),
                ('prev_owner_id', models.IntegerField(verbose_name='id предыдущего владельца')),
                ('manufacture_date', models.DateField(verbose_name='дата выпуска')),
                ('cur_license_expires', models.DateField(verbose_name='права владельца истекают')),
                ('made_in_country', models.CharField(max_length=100, verbose_name='страна выпуска')),
            ],
            options={
                'verbose_name': 'transport_info',
                'verbose_name_plural': 'transport_info',
            },
        ),
        migrations.CreateModel(
            name='transport_owners_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200, verbose_name='фио владельца')),
                ('owner_gender', models.CharField(max_length=10, verbose_name='пол владельца')),
                ('passport', models.CharField(max_length=50, verbose_name='паспорт владельца')),
                ('birth_date', models.DateField(verbose_name='дата рождения владельца')),
                ('citizenship', models.CharField(max_length=100, verbose_name='гражданство владельца')),
            ],
            options={
                'verbose_name': 'transport_owner_info',
                'verbose_name_plural': 'transport_owners_info',
            },
        ),
        migrations.CreateModel(
            name='transport_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='тип транспорта')),
            ],
            options={
                'verbose_name': 'transport_type',
                'verbose_name_plural': 'transport_types',
            },
        ),
    ]
