# Generated by Django 3.2.18 on 2023-05-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport_info',
            name='prev_owner_id',
        ),
        migrations.AlterField(
            model_name='transport_info',
            name='type_id',
            field=models.IntegerField(choices=[(1, 'Самолет'), (2, 'Поезд'), (3, 'Автобус'), (4, 'Легковой автомобиль'), (5, 'Водный транспорт'), (6, 'Вертолет')], default='4', verbose_name='тип транспорта'),
        ),
        migrations.AlterField(
            model_name='transport_owners_info',
            name='birth_date',
            field=models.DateField(max_length=100, verbose_name='дата рождения владельца'),
        ),
        migrations.AlterField(
            model_name='transport_owners_info',
            name='owner_gender',
            field=models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], default='Ж', max_length=100, verbose_name='пол владельца'),
        ),
        migrations.AlterField(
            model_name='transport_owners_info',
            name='passport',
            field=models.CharField(max_length=500, verbose_name='паспорт владельца'),
        ),
    ]
